# Generated by Django 4.1.7 on 2023-03-29 17:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_treinador_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treinador',
            new_name='trainer',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='nome_treinador',
            new_name='name_trainer',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='sobrenome',
            new_name='surname',
        ),
    ]
